/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as MediaCategoryRouteImport } from './routes/media.$category'
import { Route as FaqsCategoryRouteImport } from './routes/faqs.$category'
import { Route as CampaignsSuccessRouteImport } from './routes/campaigns.success'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsFailedRouteImport } from './routes/campaigns.failed'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCategoryRoute = MediaCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MediaRoute,
} as any)
const FaqsCategoryRoute = FaqsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => FaqsRoute,
} as any)
const CampaignsSuccessRoute = CampaignsSuccessRouteImport.update({
  id: '/campaigns/success',
  path: '/campaigns/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsFailedRoute = CampaignsFailedRouteImport.update({
  id: '/campaigns/failed',
  path: '/campaigns/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/failed': typeof CampaignsFailedRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/success': typeof CampaignsSuccessRoute
  '/faqs/$category': typeof FaqsCategoryRoute
  '/media/$category': typeof MediaCategoryRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/faqs/': typeof FaqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/failed': typeof CampaignsFailedRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/success': typeof CampaignsSuccessRoute
  '/faqs/$category': typeof FaqsCategoryRoute
  '/media/$category': typeof MediaCategoryRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/faqs': typeof FaqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/chats': typeof ChatsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/campaigns/failed': typeof CampaignsFailedRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/success': typeof CampaignsSuccessRoute
  '/faqs/$category': typeof FaqsCategoryRoute
  '/media/$category': typeof MediaCategoryRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/faqs/': typeof FaqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/chats'
    | '/login'
    | '/media'
    | '/reset-password'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns/failed'
    | '/campaigns/new'
    | '/campaigns/success'
    | '/faqs/$category'
    | '/media/$category'
    | '/campaigns/'
    | '/faqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/chats'
    | '/login'
    | '/media'
    | '/reset-password'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns/failed'
    | '/campaigns/new'
    | '/campaigns/success'
    | '/faqs/$category'
    | '/media/$category'
    | '/campaigns'
    | '/faqs'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/chats'
    | '/login'
    | '/media'
    | '/reset-password'
    | '/settings'
    | '/campaigns/$campaignId'
    | '/campaigns/failed'
    | '/campaigns/new'
    | '/campaigns/success'
    | '/faqs/$category'
    | '/media/$category'
    | '/campaigns/'
    | '/faqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  ChatsRoute: typeof ChatsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  CampaignsFailedRoute: typeof CampaignsFailedRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsSuccessRoute: typeof CampaignsSuccessRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$category': {
      id: '/media/$category'
      path: '/$category'
      fullPath: '/media/$category'
      preLoaderRoute: typeof MediaCategoryRouteImport
      parentRoute: typeof MediaRoute
    }
    '/faqs/$category': {
      id: '/faqs/$category'
      path: '/$category'
      fullPath: '/faqs/$category'
      preLoaderRoute: typeof FaqsCategoryRouteImport
      parentRoute: typeof FaqsRoute
    }
    '/campaigns/success': {
      id: '/campaigns/success'
      path: '/campaigns/success'
      fullPath: '/campaigns/success'
      preLoaderRoute: typeof CampaignsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/failed': {
      id: '/campaigns/failed'
      path: '/campaigns/failed'
      fullPath: '/campaigns/failed'
      preLoaderRoute: typeof CampaignsFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MediaRouteChildren {
  MediaCategoryRoute: typeof MediaCategoryRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaCategoryRoute: MediaCategoryRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  ChatsRoute: ChatsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  CampaignsFailedRoute: CampaignsFailedRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsSuccessRoute: CampaignsSuccessRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  FaqsIndexRoute: FaqsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
